// Generated by CoffeeScript 1.6.2
(function() {
  window.BasicTipTests = function(description, tipGenerator) {
    return describe("Tourist.Tip " + description, function() {
      beforeEach(function() {
        loadFixtures('tour.html');
        this.model = new Tourist.Model({
          current_step: null
        });
        return this.s = tipGenerator.call(this);
      });
      afterEach(function() {
        return Tourist.Tip.Base.destroy();
      });
      return describe('basics', function() {
        return it('inits', function() {
          return expect(this.s.options.model instanceof Tourist.Model).toEqual(true);
        });
      });
    });
  };

  BasicTipTests('with Tourist.Tip.Simple', function() {
    return new Tourist.Tip.Simple({
      model: this.model
    });
  });

}).call(this);
