// Generated by CoffeeScript 1.6.2
(function() {
  BasicTipTests('with Tourist.Tip.Bootstrap', function() {
    return new Tourist.Tip.Bootstrap({
      model: this.model
    });
  });

  BasicTourTests('with Tourist.Tip.Bootstrap', function() {
    return new Tourist.Tour({
      stepOptions: this.options,
      steps: this.steps,
      cancelStep: this.finalQuit,
      successStep: this.finalSucceed,
      tipClass: 'Bootstrap'
    });
  });

  xdescribe("Tourist.Tip.Bootstrap specific", function() {
    beforeEach(function() {
      loadFixtures('tour.html');
      this.model = new Tourist.Model({
        current_step: null
      });
      return this.s = new Tourist.Tip.Bootstrap({
        model: this.model
      });
    });
    afterEach(function() {
      return Tourist.Tip.Base.destroy();
    });
    return describe('setTarget()', function() {
      return it('will set the @target', function() {
        var el, target;

        el = $('#target-one');
        this.s.setTarget(el, {});
        target = this.s.qtip.get('position.target');
        return expect(target).toEqual(el);
      });
    });
  });

  describe("Tourist.Tip.BootstrapTip", function() {
    beforeEach(function() {
      loadFixtures('tour.html');
      return this.s = new Tourist.Tip.BootstrapTip();
    });
    afterEach(function() {
      return this.s.destroy();
    });
    return describe('setTarget()', function() {
      return it('will set the @target', function() {
        var el;

        return el = $('#target-one');
      });
    });
  });

}).call(this);
